<a href="https://colab.research.google.com/github/Neiscafe/cadeiras-uninter/blob/main/codelabs/codelab-01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Método de Gauss-Seidel

Sistema utilizado:

2t + x + n = 39

0,3t + 2x + 0,25n = 13

t + x + 2n = 45

Equações utilizadas:

t = (-x - n + 39)/2

x = (-0,3t - 0,25n + 13)/2

n = (-t - x + 45)/2

In [ ]:
from numpy import linalg as la
import numpy as np

t = 0.0
x = 0.0
n = 0.0
k = 0

mX = [[t], [x], [n]]


Para o método de Gauss-Seidel, é necessário isolar cada variável do sistema de equações, para isso, deve ser verificado se o módulo do coeficiente da variável isolada é maior ou igual à soma dos módulos dos coeficientes restantes na equação.

In [13]:
erroT = False
erroX = False
erroN = False
while erroT==False and erroX==False and erroN==False:
  t1 = (39-x-n)/2
  x1 = (13-(0.3*t1)-(0.25*n))
  n1 = (45-t1-x1)/2
  erroT = t1<0.001 or t1 == t
  erroX = x1<0.001 or x1 == x
  erroN = n1<0.001 or n1 == n
  if erroT==False and erroX==False and erroN==False:
    t = t1
    x = x1
    n = n1
    k = k+1
  print("t1 = ",t1)
  print("x1 = ",x1)
  print("n1 = ",n1)
  print("k = ",k)
print("t =", t)
print("x =", x)
print("n =", n)
print("k =", k)

NameError: name 'x' is not defined

# APOL 1 Ex. 3

Utilizando o processo de Gauss-Seidel com precisão de 10-2 e realizando os cálculos com arredondamento na sexta casa decimal, que resultados são obtidos para o sistema:


x1+8x2+2x3=10


15x1+x2+2x3=13


x1+2x2+3x3=-4

Fórmulas:

13-15x1=x2+2x3  =>  x1 = (-x2-x3+13)/15

10-8x2 = x1+2x3  => x2 = (-x1-2x3+10)/8

-4-3x3 = x1+2x2  => x3 = (-x1-2x2+4)/3

In [16]:
from numpy import linalg as la
import numpy as np
x1 = 0.0
x2 = 0.0
x3 = 0.0
k = 0

while(True):
  parada = False
  _x1 = (-1*x2-1*x3+13)/15
  _x2 = (-1*_x1-2*x3+10)/8
  _x3 = (-1*_x1-2*_x2+4)/3
  parada = _x1-x1<0.01 and _x2-x2<0.01 and _x3-x3<0.01
  if parada:
    break
  x1 = _x1
  x2 = _x2
  x3 = _x3
  k = k+1
print("t = ",x1)
print("x = ",x2)
print("n = ", x3)
print("k = ", k)


t =  0.7708657407407408
x =  1.0650653935185186
n =  0.36633449074074065
k =  3


# Regra de Cramer

In [11]:
from numpy import matrix, linalg
import numpy as np

print("Solução pelo Método de Cramer")
mA = np.array([[8.165956, 5.000000], [2.000000, 6.647982]])
mB = np.array([[0.000011], [0.020761]])
print(mA)
print(mB)


mT = np.copy(mA);
mT[0][0] = mB[0][0]
mT[1][0] = mB[1][0]
# mT[2][0] = mB[2][0]

print(mT)

mX = np.copy(mA);
mX[0][1] = mB[0][0]
mX[1][1] = mB[1][0]
# mX[2][1] = mB[2][0]
print(mX)
# mZ = np.copy(mA);
# mZ[0][2] = mB[0][0]
# mZ[1][2] = mB[1][0]
# mZ[2][2] = mB[2][0]
# print(mZ)
detA = np.linalg.det(mA)
detT = np.linalg.det(mT)
detX = np.linalg.det(mX)
# detZ = np.linalg.det(mZ)

s1 = detT/detA
s2 = detX/detA
# s3 = detZ/detA
print(fr"{s1} | {s2} ")


Solução pelo Método de Cramer
[[8.165956 5.      ]
 [2.       6.647982]]
[[1.1000e-05]
 [2.0761e-02]]
[[1.100000e-05 5.000000e+00]
 [2.076100e-02 6.647982e+00]]
[[8.165956e+00 1.100000e-05]
 [2.000000e+00 2.076100e-02]]
-0.0023422578006190883 | 0.0038275548281024503 


# Algoritmo que resolve sistemas de equação não-linear por Newton

In [12]:
import numpy as np

def F(x):
    """
    Define o sistema de equações não-lineares na forma F(X) = 0.

    Args:
        x (np.array): Vetor de entrada [x1, x2].

    Returns:
        np.array: Vetor com o resultado das funções [f1, f2].
    """
    x1 = x[0]
    x2 = x[1]


    # AJUSTAR AQUI


    f1 = 3.0 * x1**2 + 5.0 * x2 - 13.0


    # AJUSTAR AQUI


    f2 = 2.0 * x1 + x2**3 - 6.0

    return np.array([f1, f2])

def J(x):
    """
    Define a Matriz Jacobiana do sistema F(X).

    Args:
        x (np.array): Vetor de entrada [x1, x2].

    Returns:
        np.array: Matriz Jacobiana 2x2.
    """


# AJUSTAR AQUI


    x1 = x[0]
    x2 = x[1]

    # J = [[df1/dx1, df1/dx2],
    #      [df2/dx1, df2/dx2]]
    return np.array([[6.0 * x1, 5.0],
                       [2.0, 3.0 * x2**2]])

def newton_system_solver(F, J, x0, tol, max_iter=50):
    """
    Resolve um sistema de equações não-lineares usando o método de Newton.

    Args:
        F (function): Função que define o sistema.
        J (function): Função que define a Matriz Jacobiana.
        x0 (np.array): Chute inicial.
        tol (float): Tolerância (precisão) para o critério de parada.
        max_iter (int): Número máximo de iterações.

    Returns:
        tuple: A solução (np.array) e o número de iterações.
    """
    x = np.array(x0, dtype=float) # Garante que estamos usando floats

    print("--- Iniciando Método de Newton ---")
    print(f"Chute Inicial x(0): {x}")
    print(f"Tolerância: {tol}\n")

    for k in range(max_iter):

        F_val = F(x)
        J_val = J(x)

        try:
            delta_x = np.linalg.solve(J_val, -F_val)
        except np.linalg.LinAlgError:
            print("Erro: Matriz Jacobiana singular. Não é possível continuar.")
            return None, k


        x = x + delta_x

        # Passo 4: Checar o critério de parada (erro relativo)
        # Usamos a norma do máximo, como no cálculo manual
        error = np.max(np.abs(delta_x) / (np.abs(x) + 1e-10)) # 1e-10 evita divisão por zero

        print(f"--- Iteração {k+1} ---")
        print(f"Vetor F(x): {F_val}")
        print(f"Correção delta_x: {delta_x}")
        print(f"Nova solução x({k+1}): {x}")
        print(f"Erro relativo: {error:.6f}\n")

        if error < tol:
            print(f"Convergência atingida após {k+1} iterações.")
            return x, k + 1

    print("Aviso: Número máximo de iterações atingido sem convergência.")
    return x, max_iter



# AJUSTAR AQUI


chute_inicial = [0.0, 0.0]
tolerancia = 1e-2

solucao, iteracoes = newton_system_solver(F, J, chute_inicial, tolerancia)

if solucao is not None:
    print("\n--- Resultado Final ---")

# AJUSTAR AQUI

    print(f"A solução para o sistema é x1 = {solucao[0]:.6f} e x2 = {solucao[1]:.6f}")
    print(f"Obtida em {iteracoes} iterações.")

--- Iniciando Método de Newton ---
Chute Inicial x(0): [0. 0.]
Tolerância: 0.01

--- Iteração 1 ---
Vetor F(x): [-13.  -6.]
Correção delta_x: [3.  2.6]
Nova solução x(1): [3.  2.6]
Erro relativo: 1.000000

--- Iteração 2 ---
Vetor F(x): [27.    17.576]
Correção delta_x: [-1.29472735 -0.73898152]
Nova solução x(2): [1.70527265 1.86101848]
Erro relativo: 0.759249

--- Iteração 3 ---
Vetor F(x): [5.02895677 3.85597765]
Correção delta_x: [-0.34235658 -0.30521779]
Nova solução x(3): [1.36291607 1.55580069]
Erro relativo: 0.251194

--- Iteração 4 ---
Vetor F(x): [0.35162408 0.49167226]
Correção delta_x: [-0.00192327 -0.06717931]
Nova solução x(4): [1.3609928  1.48862138]
Erro relativo: 0.045129

--- Iteração 5 ---
Vetor F(x): [1.10969132e-05 2.07610781e-02]
Correção delta_x: [ 0.00234225 -0.00382757]
Nova solução x(5): [1.36333505 1.48479382]
Erro relativo: 0.002578

Convergência atingida após 5 iterações.

--- Resultado Final ---
A solução para o sistema é x1 = 1.363335 e x2 = 1.484794
Obti

# Eliminação de Gauss

In [17]:
import numpy as np

def eliminacao_gauss(A, b):
    """
    Resolve um sistema de equações lineares Ax = b usando o método de
    Eliminação de Gauss com pivoteamento parcial.

    Args:
        A (np.array): Matriz de coeficientes (quadrada).
        b (np.array): Vetor de resultados.

    Returns:
        np.array: Vetor da solução x, ou None se o sistema não tiver solução única.
    """
    n = len(b)
    # Garante que as matrizes usem ponto flutuante para as divisões
    A = A.astype(float)
    b = b.astype(float)

    # Construção da matriz aumentada [A|b]
    M = np.hstack([A, b.reshape(-1, 1)])

    print("--- Matriz Aumentada Inicial ---")
    print(M)
    print("-" * 30)

    # --- Fase 1: Eliminação Progressiva (com Pivoteamento Parcial) ---
    for j in range(n):
        # Pivoteamento: encontrar a linha com o maior pivô
        max_row_index = np.argmax(np.abs(M[j:, j])) + j

        # Trocar a linha atual (j) com a linha do maior pivô
        if max_row_index != j:
            M[[j, max_row_index]] = M[[max_row_index, j]]
            print(f"\n(Pivoteamento) Trocou linha {j+1} com {max_row_index+1}")
            print(M)

        # Verificar se o pivô é zero (sistema singular ou com múltiplas soluções)
        if M[j, j] == 0:
            print("Erro: O sistema não tem solução única (pivô nulo).")
            return None

        # Eliminação: zerar os elementos abaixo do pivô
        for i in range(j + 1, n):
            fator = M[i, j] / M[j, j]
            M[i, j:] = M[i, j:] - fator * M[j, j:]

        print(f"\n--- Após zerar a coluna {j+1} ---")
        print(M)

    # --- Fase 2: Substituição Regressiva ---
    x = np.zeros(n)

    # Resolve para a última variável primeiro
    x[n-1] = M[n-1, n] / M[n-1, n-1]

    # Itera de baixo para cima para encontrar as outras variáveis
    for i in range(n - 2, -1, -1):
        soma_ax = np.dot(M[i, i+1:n], x[i+1:n])
        x[i] = (M[i, n] - soma_ax) / M[i, i]

    return x

# --- Exemplo de Uso ---
# Usando o mesmo sistema da questão anterior:
# 15x1 + x2 + 2x3 = 13
# x1 + 8x2 + 2x3 = 10
# x1 + 2x2 + 3x3 = -4

# Matriz de coeficientes
A = np.array([[15, 1, 2],
              [1, 8, 2],
              [1, 2, 3]])

# Vetor de resultados
b = np.array([13, 10, -4])

# Chamando a função para resolver o sistema
solucao = eliminacao_gauss(A, b)

# Exibindo o resultado final
if solucao is not None:
    print("\n--- Resultado Final ---")
    print(f"A solução para o sistema é: {solucao}")
    print(f"x1 = {solucao[0]:.6f}")
    print(f"x2 = {solucao[1]:.6f}")
    print(f"x3 = {solucao[2]:.6f}")

--- Matriz Aumentada Inicial ---
[[15.  1.  2. 13.]
 [ 1.  8.  2. 10.]
 [ 1.  2.  3. -4.]]
------------------------------

--- Após zerar a coluna 1 ---
[[15.          1.          2.         13.        ]
 [ 0.          7.93333333  1.86666667  9.13333333]
 [ 0.          1.93333333  2.86666667 -4.86666667]]

--- Após zerar a coluna 2 ---
[[15.          1.          2.         13.        ]
 [ 0.          7.93333333  1.86666667  9.13333333]
 [ 0.          0.          2.41176471 -7.09243697]]

--- Após zerar a coluna 3 ---
[[15.          1.          2.         13.        ]
 [ 0.          7.93333333  1.86666667  9.13333333]
 [ 0.          0.          2.41176471 -7.09243697]]

--- Resultado Final ---
A solução para o sistema é: [ 1.1358885   1.84320557 -2.94076655]
x1 = 1.135889
x2 = 1.843206
x3 = -2.940767


# Gauss-Jordan

In [18]:
import numpy as np

def gauss_jordan(A, b):
    """
    Resolve um sistema de equações lineares Ax = b usando o método de Gauss-Jordan
    com pivoteamento parcial.

    Args:
        A (np.array): Matriz de coeficientes (quadrada).
        b (np.array): Vetor de resultados.

    Returns:
        np.array: Vetor da solução x, ou None se o sistema não tiver solução única.
    """
    n = len(b)
    # Garante que as matrizes usem ponto flutuante
    A = A.astype(float)
    b = b.astype(float)

    # Construção da matriz aumentada [A|b]
    M = np.hstack([A, b.reshape(-1, 1)])

    print("--- Matriz Aumentada Inicial ---")
    print(M)
    print("-" * 30)

    # Loop principal para cada coluna/pivô
    for j in range(n):
        # Passo 1: Pivoteamento Parcial
        max_row_index = np.argmax(np.abs(M[j:, j])) + j

        if max_row_index != j:
            M[[j, max_row_index]] = M[[max_row_index, j]]
            print(f"\n(Pivoteamento) Trocou linha {j+1} com {max_row_index+1}")

        # Verificar se o pivô é zero
        pivot = M[j, j]
        if pivot == 0:
            print("Erro: O sistema não tem solução única (pivô nulo).")
            return None

        # Passo 2: Normalização da linha do pivô
        M[j, :] = M[j, :] / pivot

        # Passo 3: Eliminação dos elementos da coluna do pivô em TODAS as outras linhas
        for i in range(n):
            if i != j:  # Não aplica a operação na própria linha do pivô
                fator = M[i, j]
                M[i, :] = M[i, :] - fator * M[j, :]

        print(f"\n--- Após processar a coluna {j+1} ---")
        print(np.round(M, 6)) # Arredonda para melhor visualização

    # A última coluna da matriz M agora é a solução
    x = M[:, n]

    return x

# --- Exemplo de Uso ---
# Usando o mesmo sistema das questões anteriores:
# 15x1 + x2 + 2x3 = 13
# x1 + 8x2 + 2x3 = 10
# x1 + 2x2 + 3x3 = -4

A = np.array([[15, 1, 2],
              [1, 8, 2],
              [1, 2, 3]])

b = np.array([13, 10, -4])

# Chamando a função para resolver o sistema
solucao = gauss_jordan(A, b)

# Exibindo o resultado final
if solucao is not None:
    print("\n--- Resultado Final ---")
    print(f"A solução para o sistema é: {solucao}")
    print(f"x1 = {solucao[0]:.6f}")
    print(f"x2 = {solucao[1]:.6f}")
    print(f"x3 = {solucao[2]:.6f}")

--- Matriz Aumentada Inicial ---
[[15.  1.  2. 13.]
 [ 1.  8.  2. 10.]
 [ 1.  2.  3. -4.]]
------------------------------

--- Após processar a coluna 1 ---
[[ 1.        0.066667  0.133333  0.866667]
 [ 0.        7.933333  1.866667  9.133333]
 [ 0.        1.933333  2.866667 -4.866667]]

--- Após processar a coluna 2 ---
[[ 1.        0.        0.117647  0.789916]
 [ 0.        1.        0.235294  1.151261]
 [ 0.        0.        2.411765 -7.092437]]

--- Após processar a coluna 3 ---
[[ 1.        0.        0.        1.135889]
 [ 0.        1.        0.        1.843206]
 [ 0.        0.        1.       -2.940767]]

--- Resultado Final ---
A solução para o sistema é: [ 1.1358885   1.84320557 -2.94076655]
x1 = 1.135889
x2 = 1.843206
x3 = -2.940767
